import { Injectable } from '@angular/core';
import { SchemesFilter } from "../models/schemes.filter";
import { PageOptions } from "../models/page.options";
import { BehaviorSubject } from "rxjs/BehaviorSubject";
import { SchemeSide } from "../models/scheme.side";

@Injectable()
export class SchemesAccessor
{
    private readonly _schemes = [
        {
            "colorSchemeId": "appleMint",
            "colorSchemeName": "Apple Mint",
            "inFavorites": false,
            "liked": true,
            "imageUrl": "https://scontent-arn2-1.xx.fbcdn.net/v/t31.0-8/17880136_1983863495175218_8889275720830076097_o.png?oh=9e4ae79ae77330a51cfca71571360f29&oe=59CCDBD5",
            "runOnThisSite": true,
            "restoreColorsOnCopy": false,
            "blueFilter": 0,
            "useDefaultSchedule": true,
            "scheduleStartHour": 0,
            "scheduleFinishHour": 24,
            "backgroundSaturationLimit": 80,
            "backgroundContrast": 50,
            "backgroundLightnessLimit": 15,
            "backgroundGraySaturation": 80,
            "backgroundGrayHue": 174,
            "textSaturationLimit": 80,
            "textContrast": 60,
            "textLightnessLimit": 90,
            "textGraySaturation": 20,
            "textGrayHue": 88,
            "linkSaturationLimit": 80,
            "linkContrast": 60,
            "linkLightnessLimit": 80,
            "linkDefaultSaturation": 50,
            "linkDefaultHue": 122,
            "borderSaturationLimit": 80,
            "borderContrast": 30,
            "borderLightnessLimit": 50,
            "borderGraySaturation": 10,
            "borderGrayHue": 122,
            "imageLightnessLimit": 80,
            "imageSaturationLimit": 100,
            "backgroundImageLightnessLimit": 40,
            "backgroundImageSaturationLimit": 100,
            "scrollbarSaturationLimit": 12,
            "scrollbarContrast": 5,
            "scrollbarLightnessLimit": 50,
            "scrollbarGrayHue": 122
        },
        {
            "colorSchemeId": "sunsetSails",
            "colorSchemeName": "Sunset Sails",
            "inFavorites": true,
            "liked": false,
            "imageUrl": "https://scontent-arn2-1.xx.fbcdn.net/v/t31.0-8/17917549_1983863505175217_5608182037326519772_o.png?oh=684a0ab40af2f83f44e69d7834439a88&oe=59D26790",
            "runOnThisSite": true,
            "restoreColorsOnCopy": false,
            "blueFilter": 30,
            "useDefaultSchedule": true,
            "scheduleStartHour": 0,
            "scheduleFinishHour": 24,
            "backgroundSaturationLimit": 80,
            "backgroundContrast": 50,
            "backgroundLightnessLimit": 15,
            "backgroundGraySaturation": 40,
            "backgroundGrayHue": 4,
            "textSaturationLimit": 80,
            "textContrast": 55,
            "textLightnessLimit": 90,
            "textGraySaturation": 20,
            "textGrayHue": 45,
            "linkSaturationLimit": 80,
            "linkContrast": 55,
            "linkLightnessLimit": 80,
            "linkDefaultSaturation": 70,
            "linkDefaultHue": 45,
            "borderSaturationLimit": 80,
            "borderContrast": 30,
            "borderLightnessLimit": 50,
            "borderGraySaturation": 20,
            "borderGrayHue": 14,
            "imageLightnessLimit": 80,
            "imageSaturationLimit": 100,
            "backgroundImageLightnessLimit": 40,
            "backgroundImageSaturationLimit": 100,
            "scrollbarSaturationLimit": 30,
            "scrollbarContrast": 5,
            "scrollbarLightnessLimit": 50,
            "scrollbarGrayHue": 36
        },
        {
            "colorSchemeId": "dimmedDust",
            "colorSchemeName": "Dimmed Dust",
            "inFavorites": true,
            "liked": true,
            "imageUrl": "https://scontent-arn2-1.xx.fbcdn.net/v/t31.0-8/17157594_1962351067326461_8209520558779490120_o.png?oh=1d3d81ec3f23a3b0331e946ad6348af4&oe=59CDCA2C",
            "runOnThisSite": true,
            "restoreColorsOnCopy": false,
            "blueFilter": 0,
            "useDefaultSchedule": true,
            "scheduleStartHour": 0,
            "scheduleFinishHour": 24,
            "backgroundSaturationLimit": 80,
            "backgroundContrast": 50,
            "backgroundLightnessLimit": 15,
            "backgroundGraySaturation": 10,
            "backgroundGrayHue": 200,
            "textSaturationLimit": 80,
            "textContrast": 54,
            "textLightnessLimit": 80,
            "textGraySaturation": 24,
            "textGrayHue": 16,
            "linkSaturationLimit": 80,
            "linkContrast": 54,
            "linkLightnessLimit": 70,
            "linkDefaultSaturation": 70,
            "linkDefaultHue": 207,
            "borderSaturationLimit": 80,
            "borderContrast": 30,
            "borderLightnessLimit": 50,
            "borderGraySaturation": 20,
            "borderGrayHue": 16,
            "imageLightnessLimit": 80,
            "imageSaturationLimit": 90,
            "backgroundImageLightnessLimit": 40,
            "backgroundImageSaturationLimit": 80,
            "scrollbarSaturationLimit": 10,
            "scrollbarContrast": 5,
            "scrollbarLightnessLimit": 50,
            "scrollbarGrayHue": 174
        },
        {
            "colorSchemeId": "morningMist",
            "colorSchemeName": "Morning Mist",
            "inFavorites": false,
            "liked": false,
            "imageUrl": "https://scontent-arn2-1.xx.fbcdn.net/v/t31.0-8/15776902_1927113247516910_1850860440997664456_o.png?oh=b74302d59217c8c2fe477a1790519fc5&oe=59FF4D1E",
            "runOnThisSite": true,
            "restoreColorsOnCopy": false,
            "blueFilter": 0,
            "useDefaultSchedule": true,
            "scheduleStartHour": 0,
            "scheduleFinishHour": 24,
            "backgroundSaturationLimit": 90,
            "backgroundContrast": 50,
            "backgroundLightnessLimit": 90,
            "backgroundGraySaturation": 10,
            "backgroundGrayHue": 200,
            "textSaturationLimit": 90,
            "textContrast": 60,
            "textLightnessLimit": 95,
            "textGraySaturation": 20,
            "textGrayHue": 199,
            "linkSaturationLimit": 90,
            "linkContrast": 60,
            "linkLightnessLimit": 100,
            "linkDefaultSaturation": 100,
            "linkDefaultHue": 231,
            "borderSaturationLimit": 90,
            "borderContrast": 40,
            "borderLightnessLimit": 95,
            "borderGraySaturation": 20,
            "borderGrayHue": 200,
            "imageLightnessLimit": 90,
            "imageSaturationLimit": 90,
            "backgroundImageLightnessLimit": 90,
            "backgroundImageSaturationLimit": 90,
            "scrollbarSaturationLimit": 15,
            "scrollbarContrast": 5,
            "scrollbarLightnessLimit": 80,
            "scrollbarGrayHue": 187
        },
        {
            "colorSchemeId": "invertedGrayscale",
            "colorSchemeName": "Inverted Grayscale",
            "inFavorites": false,
            "liked": false,
            "imageUrl": "https://scontent-arn2-1.xx.fbcdn.net/v/t31.0-8/17016890_1962351083993126_8861157301122852580_o.png?oh=69e4008c91c4e6cef8238ea75a55f580&oe=59FDAAC6",
            "runOnThisSite": true,
            "restoreColorsOnCopy": false,
            "blueFilter": 0,
            "useDefaultSchedule": true,
            "scheduleStartHour": 0,
            "scheduleFinishHour": 24,
            "backgroundSaturationLimit": 10,
            "backgroundContrast": 50,
            "backgroundLightnessLimit": 10,
            "backgroundGraySaturation": 0,
            "backgroundGrayHue": 0,
            "textSaturationLimit": 10,
            "textContrast": 50,
            "textLightnessLimit": 80,
            "textGraySaturation": 0,
            "textGrayHue": 0,
            "linkSaturationLimit": 10,
            "linkContrast": 50,
            "linkLightnessLimit": 80,
            "linkDefaultSaturation": 10,
            "linkDefaultHue": 231,
            "borderSaturationLimit": 10,
            "borderContrast": 30,
            "borderLightnessLimit": 50,
            "borderGraySaturation": 0,
            "borderGrayHue": 0,
            "imageLightnessLimit": 75,
            "imageSaturationLimit": 10,
            "backgroundImageLightnessLimit": 30,
            "backgroundImageSaturationLimit": 10,
            "scrollbarSaturationLimit": 0,
            "scrollbarContrast": 5,
            "scrollbarLightnessLimit": 50,
            "scrollbarGrayHue": 0
        },
        {
            "colorSchemeId": "invertedLight",
            "colorSchemeName": "Inverted Light",
            "inFavorites": false,
            "liked": false,
            "imageUrl": "https://scontent-arn2-1.xx.fbcdn.net/v/t31.0-8/17017218_1962351090659792_3108768005585377946_o.png?oh=3e1d77141a3b3db608b7c64c72f99f2c&oe=59CCE7EF",
            "runOnThisSite": true,
            "restoreColorsOnCopy": false,
            "blueFilter": 0,
            "useDefaultSchedule": true,
            "scheduleStartHour": 0,
            "scheduleFinishHour": 24,
            "backgroundSaturationLimit": 80,
            "backgroundContrast": 50,
            "backgroundLightnessLimit": 10,
            "backgroundGraySaturation": 0,
            "backgroundGrayHue": 0,
            "textSaturationLimit": 80,
            "textContrast": 50,
            "textLightnessLimit": 70,
            "textGraySaturation": 0,
            "textGrayHue": 0,
            "linkSaturationLimit": 80,
            "linkContrast": 50,
            "linkLightnessLimit": 70,
            "linkDefaultSaturation": 40,
            "linkDefaultHue": 231,
            "borderSaturationLimit": 80,
            "borderContrast": 30,
            "borderLightnessLimit": 70,
            "borderGraySaturation": 0,
            "borderGrayHue": 0,
            "imageLightnessLimit": 75,
            "imageSaturationLimit": 100,
            "backgroundImageLightnessLimit": 40,
            "backgroundImageSaturationLimit": 100,
            "scrollbarSaturationLimit": 0,
            "scrollbarContrast": 5,
            "scrollbarLightnessLimit": 50,
            "scrollbarGrayHue": 0
        }

    ];

    public getSchemes(filter: SchemesFilter, pageOptions: PageOptions)
    {
        filter.name = filter.name ? filter.name.toLowerCase() : "";
        const totalSchemes =
            this._schemes.filter(s =>
                (!filter.name || s.colorSchemeName.toLowerCase().indexOf(filter.name) !== -1)
                &&
                (filter.side == SchemeSide.None
                    || filter.side == SchemeSide.Dark && s.backgroundLightnessLimit < 50
                    || filter.side == SchemeSide.Light && s.backgroundLightnessLimit > 50)
                &&
                (!filter.favorites || s.inFavorites)
                &&
                (!filter.liked || s.liked)
            );
        pageOptions.length = totalSchemes.length;
        if (pageOptions.pageIndex >= pageOptions.length / pageOptions.pageSize)
        {
            pageOptions.pageIndex = Math.max(Math.ceil(pageOptions.length / pageOptions.pageSize) - 1, 0);
        }
        return new BehaviorSubject(
            {
                filter: filter,
                pageOptions: pageOptions,
                schemes: totalSchemes.slice(pageOptions.pageIndex * pageOptions.pageSize, (pageOptions.pageIndex + 1) * pageOptions.pageSize)
            })
            .asObservable();
    }
}
