apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: portal
  name: portal
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  strategy: {}
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - image: localhost:5000/midnightlizard.web.portal
        name: portal
        ports:
          - containerPort: 80
            protocol: TCP
        imagePullPolicy: Always
        resources: {}
      restartPolicy: Always
status: {}
