apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal
  name: portal
spec:
  clusterIP: 10.0.0.32
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: portal
  type: NodePort
